---
server:
  port: 9080

sampleservice:
  ribbon:
    DeploymentContextBasedVipAddresses: sample-hystrix-service
    ReadTimeout: 10000
    MaxAutoRetries: 2

hystrix:
  command:
    RemoteMessageClientCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    RemoteMessageAnnotationClient:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
